[[services]]
name = "api-gateway"
dir = "microservices/api-gateway"

[[services]]
name = "auth-service"
dir = "microservices/auth-service"

[[services]]
name = "booking-service"
dir = "microservices/booking-service"

[[services]]
name = "frontend"
dir = "microservices/frontend"
